import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="sticky-header">
          <div className="header">
            <h1 style={{fontWeight: "lighter"}}>loli.</h1>
            <h1 className="lgbt lgbt-animated">lgbt</h1>
          </div>
          <p style={{marginTop: "-20px"}}><em>The <strong>serious</strong> URL shortener.</em></p>
        </div>

        <div className="sticky-footer">
          <p>Made without &lt;3 by <a href="https://github.com/Steviegt6/">Tomat</a> | Fully open-source on <a href="https://github.com/Steviegt6/loli/">GitHub</a></p>
        </div>
      </main>
    </div>
  );
};

export default Home;
